version: "3"
services:

  mysql:
    image: mysql:5.6
    command: --sql_mode=NO_ENGINE_SUBSTITUTION --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - mysqldata:/var/lib/mysql/
    ports:
     - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=application

  memcached:
    image: memcached:1.4

  redis:
    image: redis:2.8
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data/

  mongo:
    image: mongo:2.6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db/

  supervisor:
    image: inisire/php:7.2-zts
    command: /usr/bin/supervisord
    links:
     - mysql
     - memcached
     - redis
     - mongo
     - mosquitto
    ports:
     - "8080:8080"
     - "8000:8000"
    volumes:
     - .:/var/www/
     - ./docker/php.ini:/usr/local/etc/php/conf.d/25-configuration-php.ini
     - ./docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
     - /tmp:/tmp

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "1884:1884"
    volumes:
      - ./docker/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  nginx:
    image: nginx:1.7
    links:
     - supervisor
    ports:
     - "80:80"
    volumes:
     - .:/var/www/
     - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro

  elasticsearch:
    image: elasticsearch:6.4.0
    links:
      - supervisor
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:6.4.0
    links:
      - elasticsearch
    ports:
      - "5601:5601"

  rabbitmq:
    image: rabbitmq:3.7.8
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  rtsp:
    image: inisire/php-rtsp
#    build:
#      dockerfile: docker/rtsp/Dockerfile
#      context: .
    ports:
      - "9001:9001"
      - "40300:40300/udp"
    command: ./bin/rtsp_server.php
    env_file:
      - .env
    user: 1000:1000
    working_dir: /var/www
    volumes:
      - .:/var/www/
      - ./docker/php.ini:/usr/local/etc/php/conf.d/25-configuration-php.ini

volumes:
  mysqldata: {}
  mongodata: {}
  redisdata: {}
  esdata: {}
  rabbitmq_data: {}