services:

    React\EventLoop\Factory: ~

    react.loop:
        class: React\EventLoop\LoopInterface
        factory: 'React\EventLoop\Factory:create'

    react.socket.server:
        class: React\Socket\Server
        arguments: ["0.0.0.0:8080", "@react.loop"]

    http_foundation.factory:
        class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory

    diactoris.factory:
        class: Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory

    react.http.server:
        class: inisire\ReactBundle\Server\Server
        arguments:
          - "@react.loop"
          - "@react.socket.server"
          - "@kernel"
          - "@http_foundation.factory"
          - "@diactoris.factory"
          - "@monolog.logger"

