home:
    resource: "@HomeBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin