# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  fractal:
    class: League\Fractal\Manager

  response.builder:
    class: PrivateDev\Utils\Json\TransformableJsonResponseBuilder
    arguments: ["@fractal"]
    shared: false

  react_connector:
    class: React\Socket\Connector
    arguments: ["@react.loop", {'dns': '127.0.0.11'}]

  Doctrine\ORM\EntityManager: '@doctrine.orm.default_entity_manager'

  BinSoul\Net\Mqtt\Client\React\ReactMqttClient:
    class: BinSoul\Net\Mqtt\Client\React\ReactMqttClient
    arguments: ["@react_connector", "@react.loop"]
    public: true

  Bunny\Async\Client:
    class: Bunny\Async\Client
    arguments:
      - '@react.loop'
      - {host:"rabbitmq", }