services:

  CommonBundle\:
    resource: '../../../../src/CommonBundle/*'
    exclude: '../../../../src/CommonBundle/{Entity,Repository}'

  CommonBundle\Service\FileUploader:
    arguments:
      $targetDir: "%upload_dir%"

  CommonBundle\Subscriber\DoctrineSubscriber:
    autowire: true
    tags:
      - { name: doctrine.event_subscriber }

  CommonBundle\Handler\MqttHandler:
    autowire: true
    public: true
    arguments:
      $mqttServer: "%mqtt_server%"
      $logger: "@logger"

  inisire\ReactBundle\Threaded\KernelFactoryInterface:
    class: KernelFactory
    arguments: ["%kernel.environment%"]