services:

  CommonBundle\:
    resource: '../../../../src/CommonBundle/*'
    exclude: '../../../../src/CommonBundle/{Entity,Repository}'

  CommonBundle\Service\FileUploader:
    arguments:
      $targetDir: "%upload_dir%"

  CommonBundle\Subscriber\DoctrineSubscriber:
    autowire: true
    tags:
      - { name: doctrine.event_subscriber }

  CommonBundle\Handler\MqttHandler:
    autowire: true
    public: true
    arguments:
      $mqttServer: "%mqtt_server%"
      $logger: "@logger"

  kernel.factory:
    class: KernelFactory
    arguments: ["%kernel.environment%"]

  inisire\ReactBundle\EventDispatcher\AsynchronousEventDispatcher:
    class: inisire\ReactBundle\EventDispatcher\AsynchronousEventDispatcher
    arguments:
      - "@kernel.factory"
      - 1
    calls:
      - [setLogger, ["@logger"]]

  async.event_dispatcher:
    alias: inisire\ReactBundle\EventDispatcher\AsynchronousEventDispatcher
    public: true