imports:
 - { resource: admin.yml }

services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  HomeBundle\Service\:
    resource: "../../Service/*"

  HomeBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  HomeBundle\Service\Bootstrap:
    public: true

  HomeBundle\Application\InhabitantsMonitorApplication:
    arguments:
      - "@react.loop"
      - "%inhabitants_ips%"
      - '@inisire\ReactBundle\Threaded\Pool'
    shared: true
    calls:
      - [setLogger, ["@logger"]]

  Elasticsearch\ClientBuilder:
    calls:
      - [setHosts, [["%elasticsearch_host%"]]]

  Elasticsearch\Client:
    factory: ['@Elasticsearch\ClientBuilder', "build"]
    public: true

