services:
  home.web_socket_server:
    autowire: true
    class: HomeBundle\Model\WebSocketServer
    arguments:
      - "@react.loop"
      - "@logger"

  home.admin.module:
    class: HomeBundle\Admin\Entity\ModuleAdmin
    arguments: [~, 'HomeBundle\Entity\Module', ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Module }

  home.admin.room:
    class: HomeBundle\Admin\Entity\RoomAdmin
    arguments: [~, 'HomeBundle\Entity\Room', ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Room }

  home.admin.unit:
    class: HomeBundle\Admin\Entity\UnitAdmin
    arguments: [~, 'HomeBundle\Entity\Unit', ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Unit }

  HomeBundle\Service\Bootstrap:
    class: HomeBundle\Service\Bootstrap
    autowire: true
    public: true