imports:
 - { resource: admin.yml }

services:

  HomeBundle\Service\Bootstrap:
    class: HomeBundle\Service\Bootstrap
    autowire: true
    public: true

  home.inhabitants_monitor:
    class: HomeBundle\Application\InhabitantsMonitorApplication
    arguments: ["@react.loop", "%inhabitants_ips%"]
    calls:
      - [setLogger, ["@logger"]]